### PR TITLE
Adding Docker file

### PR DESCRIPTION
**Pull request by automationdream**

### CODE REVIEW

**Comment by automationdream** [comment]
There is a need to mount volume in docker containing the dataset, would you please guide me where I can find it?

**Review by michalmaj — COMMENTED** [review]
All correct.

**Comment by ziobron** [comment]
Thanks @michalmaj for Code Review.
🏅 1 XP granted

**Review by michalmaj — COMMENTED** [review]
All good.

**Comment by ziobron** [comment]
Thanks @michalmaj for Code Review.
🏅 1 XP granted

**Review by RyszardHalapacz — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @RyszardHalapacz for Code Review.
🏅 1 XP granted

**Comment by ziobron** [comment]
Your PR was merged!
🏅 2 XP granted. Thanks @automationdream for making course materials better!

**Pull request merged**
