### PR TITLE
Python

### PR DESCRIPTION
**Pull request by michalmaj**
DeepLabv3+ - Building Blocks

### CODE REVIEW

**Review by ziobron — COMMENTED** [review]
please add requirements.txt file and a script for unpacking dataset

**Comment by automationdream** [comment]
Hi @michalmaj, very cool! I wish to help you to set up the observability layer for the experiments (ML Flow), lets contact on a priv Discord.

**Review by RyszardHalapacz — APPROVED** [review]

**Comment by ziobron** [comment]
Thanks @RyszardHalapacz for Code Review.
🏅 1 XP granted

**Comment by ziobron** [comment]
Your PR was merged!
🏅 2 XP granted. Thanks @michalmaj for making course materials better!

**Pull request merged**
